### ISSUE TITLE
Can't start extraterm

### ISSUE THREAD

**Issue by BarbzYHOOL** [sedwards2009/extraterm#100]
Ubuntu 14.04

Double click on the file and it doesn't do anything

So I tried to run it from another terminal and here are the errors:

```
./extraterm                                                                                                                               ⌚ 15:27:57
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/user/my_programs/extraterm-0.35.2-linux-x64/resources/app/extraterm/resources/node-sass-binary/linux-x64-57/binding.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at module.exports (/home/user/my_programs/extraterm-0.35.2-linux-x64/resources/app/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/home/user/my_programs/extraterm-0.35.2-linux-x64/resources/app/node_modules/node-sass/lib/index.js:14:35)
^C⏎   
```

**Comment by sedwards2009** [comment]
The error message is saying that your system's glibc is really old, because isn't surprising since it is Ubuntu 14.04. I already take care to make it run on older glibc/Ubuntu versions but I don't go back quite that far. I will have a look to see if it is possible to build something that does work on your system though.

**Comment by sedwards2009** [comment]
Ubuntu 140.04 is now past its support life span or is very close to it. This issue is unlikely to be addressed, so I'm going to close this issue.
