### ISSUE TITLE
Doesn't build in git source build because of "font-manager" via a change in nan

### ISSUE THREAD

**Issue by SolarAquarion** [sedwards2009/extraterm#140]
```
> `gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/solaraquarion/pkgbuild/extraterm-git/src/extraterm/node_modules/font-manager/build'
>   CXX(target) Release/obj.target/fontmanager/src/FontManager.o
> In file included from ../node_modules/nan/nan.h:194,
>                  from ../src/FontManager.cc:5:
> ../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
> ../node_modules/nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
>    return obj->ForceSet(GetCurrentContext(), key, value, attribs);
>                ^~~~~~~~
> ../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
> ../node_modules/nan/nan_maybe_43_inl.h:220:17: error: ‘class v8::Array’ has no member named ‘CloneElementAt’
>    return array->CloneElementAt(GetCurrentContext(), index);
>                  ^~~~~~~~~~~~~~
> In file included from ../node_modules/nan/nan_new.h:189,
>                  from ../node_modules/nan/nan.h:200,
>                  from ../src/FontManager.cc:5:
> ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
> ../node_modules/nan/nan_implementation_12_inl.h:40:38: error: no matching function for call to ‘v8::BooleanObject::New(bool&)’
>    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                                       ^
> In file included from /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:63,
>                  from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h:5035:23: note: candidate: ‘static v8::Local<v8::Value> v8::BooleanObject::New(v8::Isolate*, bool)’
>    static Local<Value> New(Isolate* isolate, bool value);
>                        ^~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h:5035:23: note:   candidate expects 2 arguments, 1 provided
> In file included from ../node_modules/nan/nan_new.h:189,
>                  from ../node_modules/nan/nan.h:200,
>                  from ../src/FontManager.cc:5:
> ../node_modules/nan/nan_implementation_12_inl.h:40:60: error: expected primary-expression before ‘>’ token
>    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                                                             ^
> ../node_modules/nan/nan_implementation_12_inl.h:40:62: error: expected primary-expression before ‘)’ token
>    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                                                               ^
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
> ../node_modules/nan/nan.h:821:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>          v8::Isolate::GetCurrent(), target, func, argc, argv);
>                                                             ^
> In file included from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:177:50: note: declared here
>                  NODE_EXTERN v8::Local<v8::Value> MakeCallback(
>                                                   ^~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h:821:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>          v8::Isolate::GetCurrent(), target, func, argc, argv);
>                                                             ^
> In file included from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:177:50: note: declared here
>                  NODE_EXTERN v8::Local<v8::Value> MakeCallback(
>                                                   ^~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
> ../node_modules/nan/nan.h:835:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>          v8::Isolate::GetCurrent(), target, symbol, argc, argv);
>                                                               ^
> In file included from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:170:50: note: declared here
>                  NODE_EXTERN v8::Local<v8::Value> MakeCallback(
>                                                   ^~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h:835:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>          v8::Isolate::GetCurrent(), target, symbol, argc, argv);
>                                                               ^
> In file included from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:170:50: note: declared here
>                  NODE_EXTERN v8::Local<v8::Value> MakeCallback(
>                                                   ^~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
> ../node_modules/nan/nan.h:849:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>          v8::Isolate::GetCurrent(), target, method, argc, argv);
>                                                               ^
> In file included from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:163:50: note: declared here
>                  NODE_EXTERN v8::Local<v8::Value> MakeCallback(
>                                                   ^~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h:849:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>          v8::Isolate::GetCurrent(), target, method, argc, argv);
>                                                               ^
> In file included from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:163:50: note: declared here
>                  NODE_EXTERN v8::Local<v8::Value> MakeCallback(
>                                                   ^~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
> ../node_modules/nan/nan.h:1467:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>      ));
>      ^
> In file included from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:177:50: note: declared here
>                  NODE_EXTERN v8::Local<v8::Value> MakeCallback(
>                                                   ^~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h:1467:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
>      ));
>      ^
> In file included from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:177:50: note: declared here
>                  NODE_EXTERN v8::Local<v8::Value> MakeCallback(
>                                                   ^~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> In file included from ../src/FontManager.cc:5:
> ../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
> ../node_modules/nan/nan.h:1707:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>      , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
>                                                               ^
> ../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
> ../node_modules/nan/nan.h:1961:16: error: no matching function for call to ‘v8::Object::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&)’
>      , attribute);
>                 ^
> In file included from /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:63,
>                  from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h:3348:37: note: candidate: ‘v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType)’
>    V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
>                                      ^~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h:3348:37: note:   no known conversion for argument 2 from ‘Nan::imp::NativeGetter’ {aka ‘void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’} to ‘v8::Local<v8::Name>’
> In file included from ../src/FontManager.cc:6:
> ../src/FontDescriptor.h: In member function ‘int FontDescriptor::getNumber(v8::Local<v8::Object>, const char*)’:
> ../src/FontDescriptor.h:152:32: warning: ‘int32_t v8::Value::Int32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
>        return value->Int32Value();
>                                 ^
> In file included from /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h:26,
>                  from /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:63,
>                  from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h:2478:46: note: declared here
>    V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
>                                               ^~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
>    declarator __attribute__((deprecated(message)))
>    ^~~~~~~~~~
> In file included from ../src/FontManager.cc:2:
> ../src/FontManager.cc: At global scope:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:570:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
>        (node::addon_register_func) (regfunc),                          \
>                                            ^
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:604:3: note: in expansion of macro ‘NODE_MODULE_X’
>    NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
>    ^~~~~~~~~~~~~
> ../src/FontManager.cc:223:1: note: in expansion of macro ‘NODE_MODULE’
>  NODE_MODULE(fontmanager, Init)
>  ^~~~~~~~~~~
> In file included from /home/solaraquarion/.node-gyp/10.14.2/include/node/node.h:63,
>                  from ../src/FontManager.cc:2:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
> /home/solaraquarion/.node-gyp/10.14.2/include/node/node_object_wrap.h:85:78:   required from here
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
>                 reinterpret_cast<Callback>(callback), type);
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
> ../node_modules/nan/nan_object_wrap.h:66:61:   required from here
> /home/solaraquarion/.node-gyp/10.14.2/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE getAvailableFonts(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = true; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
> ../src/FontManager.cc:213:67:   required from here
> ../src/FontManager.cc:108:74: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>  v_queue_work(uv_default_loop(), &req->work, getAvailableFontsAsync, (uv_after_work_cb) asyncCallback);
>                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE getAvailableFonts(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = false; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
> ../src/FontManager.cc:214:72:   required from here
> ../src/FontManager.cc:108:74: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE findFonts(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = true; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
> ../src/FontManager.cc:215:51:   required from here
> ../src/FontManager.cc:135:66: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>      uv_queue_work(uv_default_loop(), &req->work, findFontsAsync, (uv_after_work_cb) asyncCallback);
>                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE findFonts(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = false; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
> ../src/FontManager.cc:216:56:   required from here
> ../src/FontManager.cc:135:66: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE findFont(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = true; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
> ../src/FontManager.cc:217:49:   required from here
> ../src/FontManager.cc:164:65: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>      uv_queue_work(uv_default_loop(), &req->work, findFontAsync, (uv_after_work_cb) asyncCallback);
>                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE findFont(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = false; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
> ../src/FontManager.cc:218:54:   required from here
> ../src/FontManager.cc:164:65: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE substituteFont(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = true; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
> ../src/FontManager.cc:219:61:   required from here
> ../src/FontManager.cc:204:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>    uv_queue_work(uv_default_loop(), &req->work, substituteFontAsync, (uv_after_work_cb) asyncCallback);
>                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> ../src/FontManager.cc: In instantiation of ‘Nan::NAN_METHOD_RETURN_TYPE substituteFont(Nan::NAN_METHOD_ARGS_TYPE) [with bool async = false; Nan::NAN_METHOD_RETURN_TYPE = void; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’:
> ../src/FontManager.cc:220:66:   required from here
> ../src/FontManager.cc:204:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
> make: *** [fontmanager.target.mk:102: Release/obj.target/fontmanager/src/FontManager.o] Error 1
> make: Leaving directory '/home/solaraquarion/pkgbuild/extraterm-git/src/extraterm/node_modules/font-manager/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
> gyp ERR! System Linux 4.19.8-zen2-1-zen
> gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build"
> gyp ERR! cwd /home/solaraquarion/pkgbuild/extraterm-git/src/extraterm/node_modules/font-manager
> `
```

**Comment by sedwards2009** [comment]
Try again using node v8.9.3. That should still work. I've updated the development.md doc with the correct version of use.

**Comment by SolarAquarion** [comment]
```
1/4] Resolving packages...
warning Resolution field "@types/node@7.0.52" is incompatible with requested version "@types/node@^8.0.24"
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Creating commands.zip
cp: no such file or directory: extraterm/src/commands
module.js:550
    throw err;
    ^

Error: Cannot find module '/build/extraterm-git/src/extraterm/node_modules/shelljs/src/exec-child.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/build/extraterm-git/src/extraterm/node_modules/shelljs/src/common.js:399
        throw e;
        ^

ShellJSInternalError: ENOENT: no such file or directory, open '/tmp/shelljs_2d4d38c84e54bdc1e877'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at execSync (/build/extraterm-git/src/extraterm/node_modules/shelljs/src/exec.js:89:17)
    at _exec (/build/extraterm-git/src/extraterm/node_modules/shelljs/src/exec.js:202:12)
    at /build/extraterm-git/src/extraterm/node_modules/shelljs/src/common.js:335:23
    at main (/build/extraterm-git/src/extraterm/build_scripts/build_packages.js:61:3)
    at Object.<anonymous> (/build/extraterm-git/src/extraterm/build_scripts/build_packages.js:399:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
error Command failed with exit code 1.
```
It fails here now

**Comment by sedwards2009** [comment]
Can I see what script you are running and what it is doing exactly?

When I build packages etc I run `yarn run package` on my Linux system and it chugs out all of the zip files etc for everything.

**Comment by SolarAquarion** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=extraterm-git
i changed it to nodejs-lts-carbon in my downstream version and  i even
tried to build it in chroot

**Comment by sedwards2009** [comment]
Your error message/log looks like something went wrong with part of the git clone during packaging.

This just worked for me with a clean git clone of extraterm and by running:

`yarn install`

`yarn run package`

...and then waiting a bit as it builds. This is on the default `master` branch. Note you don't have to run `yarn run build` before package. What package does is grab a fresh copy of the git repo in `build_tmp` and then do the rest of the commands to build all of the different parts.

I'm using node v8.9.3 and yarn 1.12.3.

Maybe I should provide you with a `yarn run package-linux` command which skips the packaging bits for non-linux platforms. Interested?

**Comment by SolarAquarion** [comment]
sounds good

**Comment by SolarAquarion** [comment]
''$ node build_scripts/build_packages.js
Fetching a clean copy of the source code from git@github.com:
sedwards2009/extraterm.git
Cloning into 'extraterm'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of
known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
cd: no such file or directory: extraterm
''

**Comment by SolarAquarion** [comment]
the packaging asks to do stuff via ssh, but if my chroot is not in the list of accessible "private keys" i'll be denied the option of downloading the fresh version

**Comment by sedwards2009** [comment]
It sounds like the package script should use https:// and not git: to grab the copy for packaging.

I'll quickly change and test that now.

**Comment by SolarAquarion** [comment]
```
warning: Could not find remote branch makepkg to clone.
fatal: Remote branch makepkg not found in upstream origin
exec: Cloning into 'extraterm'...
warning: Could not find remote branch makepkg to clone.
fatal: Remote branch makepkg not found in upstream origin

cd: no such file or directory: extraterm
```
Arch creates a fork of the original code, a "clean version" to do the build, it look for a fork called makepkg which causes it to fail, oh, fun

**Comment by sedwards2009** [comment]
BTW, I just added a `package-linux-zip-only` script to run for packaging. Now you can do

`yarn run package-linux-zip-only`

and that should save some build time and disk space.

**Comment by sedwards2009** [comment]
The package script pulls the git URL out of the `package.json`. I guess I could change it to look at the local git repo it is running from.

**Comment by sedwards2009** [comment]
I've made the change :point_up:  . The package script now uses the git URL from the current git repo.

**Comment by SolarAquarion** [comment]
''''Fetching a clean copy of the source code from
/home/solaraquarion/pkgbuild/extraterm-git/extraterm
Cloning into 'extraterm'...
warning: --depth is ignored in local clones; use file:// instead.
warning: Could not find remote branch makepkg to clone.
fatal: Remote branch makepkg not found in upstream origin
fatal: the remote end hung up unexpectedly
exec: Cloning into 'extraterm'...
warning: --depth is ignored in local clones; use file:// instead.
warning: Could not find remote branch makepkg to clone.
fatal: Remote branch makepkg not found in upstream origin
fatal: the remote end hung up unexpectedl
''''''''

Your building pattern is causing headaches, lol

**Comment by SolarAquarion** [comment]
"
exec("git clone --depth 1 -b " + info.branch + " " + gitUrl);"

**Comment by sedwards2009** [comment]
@SolarAquarion  The packaging system is really made for me and all the different platforms I support. If you like, I could change it a bit to support building zips directly from the source without the extra git download step. i.e. just make it work like every other normal piece of software in the world.

**Comment by SolarAquarion** [comment]
True enough, take your time
