### ISSUE TITLE
Cannot start extraterm

### ISSUE THREAD

**Issue by Syphdias** [sedwards2009/extraterm#253]
I tried 3 "different" versions all with the same error. [extraterm-bin](https://aur.archlinux.org/packages/extraterm-bin/), the latest release from github 0.49.1 (which should be identical to the AUR package which only copies binaries) and I also tired the latest nightly build.

I don't get a new window but the process keeps running. Any ideas?

```
./extraterm
2020-03-10 17:32:41.223 INFO [MainConfig #0] Looking for application_paths.json at '/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/application_paths.json'
2020-03-10 17:32:41.225 INFO [main #0] Recording logs to  /home/syphdias/.config/extraterm/extraterm.log
2020-03-10 17:32:41.227 INFO [MainExtensionManager #0] Read extension metadata from 'audio-viewer'.
2020-03-10 17:32:41.228 INFO [MainExtensionManager #0] Read extension metadata from 'community-syntax-themes'.
2020-03-10 17:32:41.228 INFO [MainExtensionManager #0] Read extension metadata from 'community-terminal-themes'.
2020-03-10 17:32:41.228 INFO [MainExtensionManager #0] Read extension metadata from 'default-keybindings'.
2020-03-10 17:32:41.229 INFO [MainExtensionManager #0] Read extension metadata from 'default-syntax-theme'.
2020-03-10 17:32:41.229 INFO [MainExtensionManager #0] Read extension metadata from 'default-terminal-theme'.
2020-03-10 17:32:41.230 INFO [MainExtensionManager #0] Read extension metadata from 'find'.
2020-03-10 17:32:41.230 INFO [MainExtensionManager #0] Read extension metadata from 'itermcolors-terminal-theme-provider'.
2020-03-10 17:32:41.231 INFO [MainExtensionManager #0] Read extension metadata from 'inject-shell-integration'.
2020-03-10 17:32:41.241 INFO [MainExtensionManager #0] Read extension metadata from 'internal-commands'.
2020-03-10 17:32:41.243 INFO [MainExtensionManager #0] Read extension metadata from 'proxy-session-backend'.
2020-03-10 17:32:41.244 INFO [MainExtensionManager #0] Read extension metadata from 'proxy-session-editor'.
2020-03-10 17:32:41.244 INFO [MainExtensionManager #0] Read extension metadata from 'terminal-title'.
2020-03-10 17:32:41.244 INFO [MainExtensionManager #0] Read extension metadata from 'textmate-syntax-theme-provider'.
2020-03-10 17:32:41.244 INFO [MainExtensionManager #0] Read extension metadata from 'text-viewer-options'.
2020-03-10 17:32:41.245 INFO [MainExtensionManager #0] Read extension metadata from 'unix-session-backend'.
2020-03-10 17:32:41.245 INFO [MainExtensionManager #0] Read extension metadata from 'unix-session-editor'.
2020-03-10 17:32:41.245 INFO [MainExtensionManager #0] Read extension metadata from 'windows-console-session-backend'.
2020-03-10 17:32:41.246 INFO [MainExtensionManager #0] Read extension metadata from 'windows-console-session-editor'.
2020-03-10 17:32:41.246 INFO [MainExtensionManager #0] Starting extension 'community-syntax-themes' in the main process.
2020-03-10 17:32:41.246 INFO [MainExtensionManager #0] Starting extension 'community-terminal-themes' in the main process.
2020-03-10 17:32:41.246 INFO [MainExtensionManager #0] Starting extension 'default-syntax-theme' in the main process.
2020-03-10 17:32:41.246 INFO [MainExtensionManager #0] Starting extension 'default-terminal-theme' in the main process.
2020-03-10 17:32:41.246 INFO [MainExtensionManager #0] Starting extension 'itermcolors-terminal-theme-provider' in the main process.
2020-03-10 17:32:41.254 DEBUG [[Main]itermcolors-terminal-theme-provider #0] ITermColorTerminalThemeProvider activating
2020-03-10 17:32:41.254 INFO [MainExtensionManager #0] Starting extension 'textmate-syntax-theme-provider' in the main process.
2020-03-10 17:32:41.255 DEBUG [[Main]textmate-syntax-theme-provider #0] TextMateSyntaxThemeProvider activating
2020-03-10 17:32:41.255 INFO [MainExtensionManager #0] Starting extension 'unix-session-backend' in the main process.
2020-03-10 17:32:41.258 DEBUG [KeybindingsIOManager #0] {filename: Mac OS X bindings.json, path: /home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extensions/DefaultKeybindings/keybindings, name: Mac OS X bindings}
2020-03-10 17:32:41.258 DEBUG [KeybindingsIOManager #0] {filename: Mac OS X with emacs bindings.json, path: /home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extensions/DefaultKeybindings/keybindings, name: Mac OS X with emacs bindings}
2020-03-10 17:32:41.258 DEBUG [KeybindingsIOManager #0] {filename: PC style bindings.json, path: /home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extensions/DefaultKeybindings/keybindings, name: PC style bindings}
2020-03-10 17:32:41.258 DEBUG [KeybindingsIOManager #0] {filename: PC with emacs style bindings.json, path: /home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extensions/DefaultKeybindings/keybindings, name: PC with emacs style bindings}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/src/main_process/Main.js:529:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/src/main_process/Main.js:103:22)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/src/main_process/Main.js:997:1)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
```

Distro and kernel:
```
Description:	Manjaro Linux
Release:	19.0.2
Codename:	Kyria
Kernel:		5.5.7-1-MANJARO
```
Note sure if important:
```
node --version
v13.9.0
```

**Comment by sedwards2009** [comment]
It is most likely a problem on the packaging side. Talk to person who packaged this.

In the mean time you can also try the Linux download from Github here.

**Comment by Syphdias** [comment]
As mentioned I tried 3 different versions. Only one of them from a "[package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=extraterm-bin)". The other two were straight from github and the latest nightly build. I'll try older versions if they have the same problem.

**Comment by Syphdias** [comment]
I tried every version on github from v0.42.0 to v0.49.1. None worked.
```
❯ for i in extraterm-*; do recho $i; timeout 1s ${i}/extraterm |tail -14; done
extraterm-0.42.0-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token  in JSON at position 4907
    at JSON.parse (<anonymous>)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:17:22)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:484:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:94:111)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:939:1)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:941:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
extraterm-0.42.1-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token  in JSON at position 4907
    at JSON.parse (<anonymous>)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.1-linux-x64/resources/app/extraterm/src/main_process/FontList.js:17:22)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:484:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:94:111)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:939:1)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:941:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
extraterm-0.42.2-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token  in JSON at position 4907
    at JSON.parse (<anonymous>)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.2-linux-x64/resources/app/extraterm/src/main_process/FontList.js:17:22)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.2-linux-x64/resources/app/extraterm/src/main_process/Main.js:484:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.2-linux-x64/resources/app/extraterm/src/main_process/Main.js:94:111)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.2-linux-x64/resources/app/extraterm/src/main_process/Main.js:939:1)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.42.2-linux-x64/resources/app/extraterm/src/main_process/Main.js:941:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
extraterm-0.43.0-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token  in JSON at position 4907
    at JSON.parse (<anonymous>)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.43.0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:17:22)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.43.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:486:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.43.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:93:111)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.43.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:952:1)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
extraterm-0.44.0-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.44.0-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.44.0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.44.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:485:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.44.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:93:111)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.44.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:951:1)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
extraterm-0.44.1-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.44.1-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.44.1-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.44.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:485:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.44.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:93:111)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.44.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:951:1)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
extraterm-0.45.0-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.45.0-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.45.0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.45.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:485:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.45.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:93:111)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.45.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:951:1)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
extraterm-0.46.0-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.46.0-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.46.0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.46.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:485:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.46.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:93:120)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.46.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:951:1)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
extraterm-0.47.0-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.47.0-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.47.0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.47.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:522:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.47.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:102:120)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.47.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:990:1)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
extraterm-0.49.0-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.49.0-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:529:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:103:22)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.0-linux-x64/resources/app/extraterm/src/main_process/Main.js:997:1)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
extraterm-0.49.1-9-g18d1d7e0-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/src/main_process/Main.js:529:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/src/main_process/Main.js:103:22)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/src/main_process/Main.js:997:1)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
extraterm-0.49.1-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: /home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
    at checkExecSyncError (child_process.js:636:11)
    at Object.execFileSync (child_process.js:654:15)
    at Object.func [as execFileSync] (electron/js2c/asar.js:155:31)
    at Object.getAvailableFontsSync (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-linux-x64/resources/app/extraterm/src/main_process/FontList.js:16:40)
    at getFonts (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:529:42)
    at main (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:103:22)
    at Object.<anonymous> (/home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-linux-x64/resources/app/extraterm/src/main_process/Main.js:997:1)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
```

**Comment by Syphdias** [comment]
```
❯ /home/syphdias/Downloads/extraterm-build/extraterm-0.49.1-9-g18d1d7e0-linux-x64/resources/app/extraterm/resources/list-fonts-json-binary/linux-x64/list-fonts-json
[1]    19458 segmentation fault (core dumped)  
```

**Comment by Syphdias** [comment]
Apparently there was an [update to another (font related) package](https://aur.archlinux.org/cgit/aur.git/log/?h=ttf-google-fonts-git) a few hours ago. Apparently this fixed the font issue :man_shrugging:
