### ISSUE TITLE
panic: Post "/command": unsupported protocol scheme "" when launching, no UI displays

### ISSUE THREAD

**Issue by belthesar** [sedwards2009/extraterm#360]
Version: extraterm-0.59.3-linux-x64
OS: Pop!_OS 21.04 (Ubuntu derivative)

Details:

Hi! Hopeful new user here trying to give extraterm a spin, but it seems I'm left in a bad state from the word go. Grabbed the latest release deb and installed, as well as the release zip. Upon starting, the following errors are emitted: 

```
┌─[ ~/Downloads/extraterm-0.59.3-linux-x64 ] 
└─▪ ./extraterm
panic: Post "/command": unsupported protocol scheme ""

goroutine 1 [running]:
main.runCommand(0x0, 0x0, 0xc000125f08, 0x13, 0xc000194088, 0x0)
        /home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:193 +0x2f3
main.runOpenWindowAtCommand(0x0, 0x0, 0xc0000180c4, 0x34, 0x401230)
        /home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:128 +0xf7
main.main()
        /home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:40 +0xb6
```
I don't suspect it's relevant, but not being incredibly hip to go, I'll toss it here anyway - go version: 
```
└─▪ go version
go version go1.16.8 linux/amd64
```

Processes `extraterm_main` do spawn and run in the background, and require killing manually to clean up. 

Happy to do some more guided digging if folks have insight. Thanks!

**Comment by belthesar** [comment]
Did a little digging which pointed me to https://github.com/sedwards2009/extraterm-launcher. I can refile this issue there if you'd like, however I'm not certain the issue is with the launcher per se. It is definitely seemingly losing the path to the IPC file, which is also not seemingly made in the config directory, so I'm not certain what's going on there. `$XDG_CONFIG_HOME` wasn't set, so I did try to set that to see if that would help, but it didn't have any improvement there. I think I'm at a loss here without further insight.

**Comment by sedwards2009** [comment]
That launcher isn't meant to blow up if something unexpected happens. It should recover by itself and launch a new Extraterm instance. Thanks.

**Comment by belthesar** [comment]
Hi there! I should clarify, which would have been far more reasonable of me to do so in my original post if I hadn't written this super early in the morning, but I was tracing this bug because Extraterm wouldn't launch for me, and thought this might be relevant. Hopefully this color helps.

**Comment by sedwards2009** [comment]
@belthesar  See my last comment #333 if Extraterm won't start up.

**Comment by belthesar** [comment]
@sedwards2009 Unfortunately, no such file exists. 
```
┌─[ ~/.config/extraterm ] 
└─▪ ls -la 
total 4
drwx------ 1 belthesar belthesar  166 Nov  3 18:45  .
drwx------ 1 belthesar belthesar 5250 Nov 21 11:19  ..
drwx------ 1 belthesar belthesar    0 Oct 29 00:44 'Crash Reports'
drwx------ 1 belthesar belthesar    0 Oct 29 00:44  Dictionaries
drwxrwxr-x 1 belthesar belthesar    0 Oct 29 18:16  extension_config
-rw-rw-r-- 1 belthesar belthesar  103 Nov  3 18:45  extraterm.log
drwxrwxr-x 1 belthesar belthesar    0 Oct 29 17:48  extraterm-qt
drwxrwxr-x 1 belthesar belthesar    0 Oct 29 00:44  keybindings
drwxrwxr-x 1 belthesar belthesar   28 Oct 29 00:44  themes
```

**Comment by nasava** [comment]
Unfortunately I am having the same issue. I do not even have a `~/.config/extraterm` folder yet. This is a freshly unpacked [extraterm-0.59.4-linux-x64.zip](https://github.com/sedwards2009/extraterm/releases/download/v0.59.4/extraterm-0.59.4-linux-x64.zip) which is producing this.

**Comment by sedwards2009** [comment]
Does this problem still occur on the latest Qt based version? (It uses the same launcher part as the old Electron version.)

**Comment by sedwards2009** [comment]
Closing due to inactivity. It is probably fixed anyway.
