### ISSUE TITLE
Error: /home/user/bin/extratermqt-0.71.1-linux-x64/node_modules/@nodegui/nodegui/build/Release/../../miniqt/6.4.1/gcc_64/lib/libQt6SvgWidgets.so.6: file too short

### ISSUE THREAD

**Issue by IvayloHrTonev** [sedwards2009/extraterm#425]
Hi,

I downloaded this - https://github.com/sedwards2009/extraterm/releases/download/v0.71.1/extraterm-commands-0.71.1.zip
Unpack it and try to start:

```
./extratermqt            
node:internal/modules/cjs/loader:1243
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/user/bin/extratermqt-0.71.1-linux-x64/node_modules/@nodegui/nodegui/build/Release/../../miniqt/6.4.1/gcc_64/lib/libQt6SvgWidgets.so.6: file too short
    at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/user/bin/extratermqt-0.71.1-linux-x64/node_modules/@nodegui/nodegui/dist/lib/utils/addon.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.12.1
panic: Post "/command": unsupported protocol scheme ""

goroutine 1 [running]:
main.runCommand({0x0, 0x0}, 0xc0000c3f08)
        /home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:200 +0x2f4
main.runOpenWindowAtCommand({0x0, 0x0}, {0xc000020064, 0x2b})
        /home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:135 +0xd9
main.main()
        /home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:40 +0x73

```

My OS is  Arch 
'I have other problems with extraterm-bin from the repo; that's why I am trying using the zip release from here.
Thank you in advance!

**Comment by sedwards2009** [comment]
There doesn't appear to be anything wrong with the zip or its contents. I just tested it here. Is there anything else you can tell me about your system?

**Comment by IvayloHrTonev** [comment]
In `/home/user/bin/extratermqt-0.71.1-linux-x64/node_modules/@nodegui/nodegui/build/Release/` I only have 

**nodegui_core.node**

Also I installed qt6-svg on system level
