### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by kruthoff** [sedwards2009/extraterm#439]
Version 0.76 doesn't start anymore on Pop!_OS 22.04 LTS x86_64.
I've purged the app and have reinstalled it, without luck.

```
[akruthoff@gazelle-akr:~$ /opt/extratermqt/extratermqt 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

panic: Post "/command": unsupported protocol scheme ""

goroutine 1 [running]:
main.runCommand({0x0, 0x0}, 0xc0000e7ec8)
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:200 +0x2e5
main.runOpenWindowAtCommand({0x0, 0x0}, {0xc00001c0dc, 0xf})
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:135 +0xd4
main.main()
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:40 +0x6a
[akruthoff@gazelle-akr:~$
```

**Comment by sedwards2009** [comment]
Is this running on Xorg or Wayland as display server?

**Comment by kruthoff** [comment]
> Is this running on Xorg or Wayland as display server?

Running on Xorg.

**Comment by LackingCats** [comment]
try running 
``
export QT_QPA_PLATFORM=xcb
``
before starting it from the command line

**Comment by paulrtcsjh** [comment]
I have this issue too, same exact message. I am running Ubuntu 24.04 and using Xorg. Running export as LackingCats suggested did not change the result.

**Comment by Ralms** [comment]
Running into the same issue on Ubuntu 22.04.05 LTS. 

```qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

panic: Post "/command": unsupported protocol scheme ""

goroutine 1 [running]:
main.runCommand({0x0, 0x0}, 0xc0000dbec8)
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:200 +0x2e5
main.runOpenWindowAtCommand({0x0, 0x0}, {0xc00001c0c4, 0xe})
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:135 +0xd4
main.main()
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:40 +0x6a
```

Doing the `export QT_QPA_PLATFORM=xcb` didn't fix it. 

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

panic: Post "/command": unsupported protocol scheme ""

goroutine 1 [running]:
main.runCommand({0x0, 0x0}, 0xc0000dbec8)
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:200 +0x2e5
main.runOpenWindowAtCommand({0x0, 0x0}, {0xc00001c0c4, 0xe})
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:135 +0xd4
main.main()
	/home/runner/work/extraterm-launcher/extraterm-launcher/cmd/extraterm-launcher/extraterm-launcher.go:40 +0x6a

```

**Comment by RedX2501** [comment]
For me it was the missing `libxcb-cursor0`

```
 sudo apt install libxcb-cursor0
```

Was enough to solve the problem.
