### ISSUE TITLE
"Error: Pty seems to have been killed already" when closing cmd.exe or powershell.exe window from the "X" on the right of the tab

### ISSUE THREAD

**Issue by corelon** [sedwards2009/extraterm#98]
When trying to close a CMD.exe  or Powershell.exe window from the "X" button on the tab I get the following exception.
This does not happen when I just type "exit" and press Enter.
It does not happen with WSL (have not tried cygwin)
Extraterm version 0.35.1 on Windows 10 1709

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Pty seems to have been killed already
    at WindowsPtyAgent.kill (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\node_modules\node-pty\lib\windowsPtyAgent.js:83:13)
    at WindowsTerminal.<anonymous> (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\node_modules\node-pty\lib\windowsTerminal.js:144:26)
    at WindowsTerminal._defer (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\node_modules\node-pty\lib\windowsTerminal.js:155:24)
    at WindowsTerminal.kill (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\node_modules\node-pty\lib\windowsTerminal.js:139:14)
    at WindowsTerminal.<anonymous> (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\node_modules\node-pty\lib\windowsTerminal.js:134:19)
    at WindowsTerminal._defer (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\node_modules\node-pty\lib\windowsTerminal.js:155:24)
    at WindowsTerminal.destroy (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\node_modules\node-pty\lib\windowsTerminal.js:133:14)
    at WindowsConsolePty.destroy (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\extensions\WindowsConsoleSessionBackend\src\WindowsConsolePty.js:66:22)
    at ptyTerm.onExit (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\extraterm\src\main_process\pty\PtyManager.js:68:21)
    at _listeners.forEach.listener (C:\Users\nikolaos.tzanos\Software\extraterm-0.35.1-win32-x64\resources\app\node_modules\extraterm-event-emitter\main.js:37:45)

[OK]

**Comment by sedwards2009** [comment]
thanks. I can easily reproduce this bug.

**Comment by shanselman** [comment]
Hit this also within a few minutes of my first use.
